modLoader="javafml"
loaderVersion="[47,)"
license="MIT License https://github.com/McJty/YouTubeModding14/blob/1.16/LICENCE"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mods]]
modId="fancytrinkets"
version="${file.jarVersion}"
displayName="Fancy Trinkets"
authors="McJty"
description='''
All kinds of useful baubles (curios)
'''

[[dependencies.fancytrinkets]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.fancytrinkets]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.fancytrinkets]]
    modId="mcjtylib"
    mandatory=true
    versionRange="[1.20-8.0.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.fancytrinkets]]
    modId="curios"
    mandatory=true
    versionRange="[1.19.2-5.1.1.0,)"
    ordering="AFTER"
    side="BOTH"
