modLoader="javafml"
loaderVersion="[40,)"
license="MIT License https://github.com/McJty/YouTubeModding14/blob/1.16/LICENCE"

[[mods]]
modId="fancytrinkets"
version="${file.jarVersion}"
displayName="Fancy Trinkets"
authors="McJty"
description='''
All kinds of useful baubles (curios)
'''

[[dependencies.fancytrinkets]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.fancytrinkets]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.fancytrinkets]]
    modId="mcjtylib"
    mandatory=true
    versionRange="[1.18-6.0.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.fancytrinkets]]
    modId="curios"
    mandatory=true
    versionRange="[1.18.2-5.0.7.0,)"
    ordering="AFTER"
    side="BOTH"
